name: Test autolabel
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run autolabel action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "bug,enhancement,question"